if: branch = master
sudo: required
language: python
services:
- docker
before_install:
- mkdir -p output
- docker pull asciidoctor/docker-asciidoctor
script:
- docker run -v $TRAVIS_BUILD_DIR/2022:/documents/ asciidoctor/docker-asciidoctor
  asciidoctor -a data-uri 2022-ssl-ball-placement-rules.adoc
- docker run -v $TRAVIS_BUILD_DIR/2022:/documents/ asciidoctor/docker-asciidoctor
  asciidoctor-pdf 2022-ssl-ball-placement-rules.adoc
- git clone https://github.com/RoboCup-SSL/technical-challenge-rules.git --single-branch --branch gh-pages $TRAVIS_BUILD_DIR/gh-pages
- cd $TRAVIS_BUILD_DIR/gh-pages
- cp $TRAVIS_BUILD_DIR/2022/*.html $TRAVIS_BUILD_DIR/2022/*.pdf .
- git config user.name "TravisCI"
- git config user.email "build-pipeline@travis-ci.org"
- git add *.html *.pdf
- git commit -m "Update GitHub Pages"
- git push "https://${GH_TOKEN}@github.com/RoboCup-SSL/technical-challenge-rules.git" gh-pages
